TRUNCATE TABLE vendedor_territorio RESTART IDENTITY CASCADE;
TRUNCATE TABLE territorio RESTART IDENTITY CASCADE;
TRUNCATE TABLE vendedor RESTART IDENTITY CASCADE;
TRUNCATE TABLE industria RESTART IDENTITY CASCADE;
TRUNCATE TABLE cliente RESTART IDENTITY CASCADE;
TRUNCATE TABLE local RESTART IDENTITY CASCADE;
TRUNCATE TABLE producto RESTART IDENTITY CASCADE;
TRUNCATE TABLE empresa RESTART IDENTITY CASCADE;
TRUNCATE TABLE categoria RESTART IDENTITY CASCADE;
TRUNCATE TABLE empresa_categoria RESTART IDENTITY CASCADE;
TRUNCATE TABLE marca RESTART IDENTITY CASCADE;
TRUNCATE TABLE venta RESTART IDENTITY CASCADE;


SELECT * FROM vendedor;
SELECT * FROM territorio;
SELECT * FROM vendedor_territorio ORDER BY ID;
SELECT * FROM industria;
SELECT * FROM cliente;
SELECT * FROM local;
SELECT * FROM producto;
SELECT * FROM empresa;
SELECT * FROM categoria;
SELECT * FROM empresa_categoria;
SELECT * FROM marca;
SELECT * FROM venta;

DROP TABLE Venta;
DROP TABLE vendedor_territorio;
DROP TABLE Local;
DROP TABLE Vendedor;
DROP TABLE Cliente;
DROP TABLE Producto;
DROP TABLE empresa_categoria;
DROP TABLE Territorio;
DROP TABLE Industria;
DROP TABLE Marca;
DROP TABLE Categoria;
DROP TABLE Empresa;